version: "3.8"

services:
  app:
    container_name: incubtek-badge-web
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    volumes:
      - ./app:/workspace/app
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  db:
    image: postgres:latest
    container_name: incubtek-badge-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  postgres-data:
