version: "3.8"

services:
  app:
    env_file:
      - .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres-data:
