# Generated by Django 4.2.5 on 2023-10-04 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0, verbose_name='Points')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('published', 'Published'), ('draft', 'Draft')], default='active', max_length=255, verbose_name='Status')),
                ('criteria', models.IntegerField(default=0, verbose_name='Criteria')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badge.model3d', verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification date')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.badge', verbose_name='Badge')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='badge.badgeuser', verbose_name='Recipient')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_badges', to='badge.badgeuser', verbose_name='Verifier')),
            ],
        ),
        migrations.CreateModel(
            name='MyBadgeUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('badge.badgeuser',),
        ),
        migrations.AddConstraint(
            model_name='assertion',
            constraint=models.UniqueConstraint(fields=('recipient', 'badge'), name='unique_recipient_badge'),
        ),
    ]
