# Generated by Django 4.2.5 on 2023-10-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeuser',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
    ]
