# Generated by Django 4.2.5 on 2023-10-03 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_alter_badgeuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('file', models.FileField(upload_to='files/', verbose_name='File')),
            ],
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badge.model3d', verbose_name='Icon'),
        ),
    ]
