# Generated by Django 4.2.5 on 2023-10-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_model3d_alter_badge_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeuser',
            name='department',
        ),
        migrations.AddField(
            model_name='badgeuser',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
    ]
