# Generated by Django 4.2.5 on 2023-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0004_remove_badgeuser_department_badgeuser_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='type',
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria',
            field=models.IntegerField(verbose_name='Criteria'),
        ),
    ]
