# Generated by Django 4.2.5 on 2023-10-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0004_alter_task_assignee_alter_task_responsible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBadgeUser',
        ),
    ]
