# Generated by Django 4.2.5 on 2023-10-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_delete_mybadgeuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
