# Generated by Django 4.2.5 on 2023-10-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0006_rename_completed_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertion',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='badge.badgeuser', verbose_name='Recipient'),
        ),
    ]
