# Generated by Django 4.2.6 on 2023-10-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0007_alter_assertion_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
